# Use the official Nginx image
FROM nginx:alpine

# Remove default Nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy HTML/CSS/JS files to Nginx web root
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80
